### ISSUE TITLE
nobackprop notebook missing imports

### ISSUE THREAD

**Issue by davidbp** [tbreloff/notebooks#2]
Hi @tbreloff 

I was trying to use your notebook/nobackprop but there are  is a cell

```julia
# this reexports Transformations and StochasticOptimization, which is what
# we'll use to minimize our function f
using Learn
```

That is not working since I don't have the Learn module. It seems it's not in your git repo.
I've tried to import LearnBase but it's not working. Could you give me a hint on what to install?

Thank you for your time and your awesome blog.

**Comment by tbreloff** [comment]
All of this stuff lives in the JuliaML org, though I sadly don't have time
for Julia projects anymore. It's highly unlikely that this notebook will
run as it is, but the other JuliaML members should be able to help point
you in the right direction.

**Comment by davidbp** [comment]
thank you for your answer,
I will ask in JuliaML but I cannot see a notebooks repo inside juliaML.

It's a great loss that you can't devote time into this. I truly liked your blog posts.
